language: node_js
node_js:
- '10'
- '12'
- '14'
deploy:
  provider: npm
  api_key:
    secure: A+FYljHdO62nNnaSopD2I4M57QAFfOjMb1SK/rMJK8OAPu47PT2+L8ZKOU58a9WPs7q889nAOcRcvZkar4apUKZF0wDSzWfEwh6OdJoXZDP24UZYF8Cf0EWb86mOXlUKktYjPP97lwWTBHjvp+bJnTYH1r4Q5zqIXfZdQngNPJNhNILrtRhx3WJJ5N/lDIf5oqQkvAdDYsIEsfkUFqE7vBk7zmpTIvrPE0/+2BsJI7O/OS61Su+WdsemowklZLabCFKARIf3/vd1U616H97cRTteg6aD2HSf81WrCbO63tjsK3YUAZSJfFtmr+QzhDA5UWWnZiIW8IcqrAKUGoeRdBO4qfsMZAGVwRLWeV7UTwbb515F6aiEN8eGUwXP2QE09F6rCawFCG82qapk3R5umhP/04uxZEc9r74gUqcWE0C2SlSUufFAkWXrGLOPqjGmLHU3PdQFa4JPLtPFxF4LOgmHaLqyaOS1g303tErBEYDlWAu6np7Ib2Y93fC4WxeAF9Gcj8eGBWuYw4clUg555n3QIGpGoULYJ6P+eivsJ9UUijMbb2px3DaLWR8IS2VptBqgjLlXiyaVpyp/ExeX2ZCvo8dvJLoLhscyC2zEtIiHRVtSF7CRTorsaHlZ088t39+p1K/+0xWUqFAttpj9E/TBbkS2OY/yxUhmi66+ijc=
  email: julian@dotcore.co.il
  skip_cleanup: true
  on:
    tags: true
env:
- I18NEXT_CONV_VER=10
before_install:
- travis_retry npm install i18next-conv@$I18NEXT_CONV_VER
script:
- npm test
after_success:
- npm run coveralls
